version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/
    networks:
      - app-networks
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
